workflows:
  buyer_workflow:
    name: CI
    instance_type: mac_mini
    # Setting the timeout for a build to 15 minutes.
    max_build_duration: 60
    environment:
      # Using the latest Flutter version.
      flutter: stable
    when:
      changeset:
        includes:
          # Only run the CI when a file in one of the following directories
          # changed.
          - "apps/buyer_app/**"
          - "packages/**"
          - "codemagic.yaml"
        excludes:
          # Don't run the CI when only .md files changed.
          - "**/*.md"
    # This workflow should trigger when a new pull request opens or updates.
    triggering:
      events:
        - pull_request
        - push
      branch_patterns: 
        - pattern: main
    scripts:
      - name: Add Dart SDK to PATH
        script: |
          echo PATH="$PATH":"$FLUTTER_ROOT/.pub-cache/bin" >> $CM_ENV
          echo PATH="$PATH":"$FLUTTER_ROOT/bin" >> $CM_ENV
      - name: Melos Bootstrap
        script: |
          dart pub global activate melos
          melos bootstrap
      - name: Run build
        script: melos run run:buyer
